repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: check-merge-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args:
          ["--py311-plus"]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: "Format with prettier"
        types: [yaml, json, markdown]
  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: Remove unused imports and unused variables
        args:
          [
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
          ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: Python code vulnerabilities checker
        args: [-r, -x, tests]
        files: .py$
  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: pytest
        args: ["-v"]
        language: system
        stages: [push]
        pass_filenames: false
        always_run: true
