"""empty message

Revision ID: c3bab67d1c3a
Revises: c3b41a20ae0b
Create Date: 2025-02-27 19:49:05.919411

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "c3bab67d1c3a"
down_revision = "c3b41a20ae0b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("api_key", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    )
    op.create_index(op.f("ix_users_api_key"), "users", ["api_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_api_key"), table_name="users")
    op.drop_column("users", "api_key")
    # ### end Alembic commands ###
